### ISSUE TITLE
Mitgliederversammlung 28.8.2019

### ISSUE THREAD

**Issue by Libermentix** [FreieMaker/orga#1]
# Mitgliederversammlung Freie Maker e.V.

|Eckdaten | &nbsp;|
|------|--------:|
|Datum |28.08.19| 
|Um    |   20:07|
|Ort   |Creator Space, Lemiers|
|Anwesende Mitglieder| 10 (Ab 20:53 11 Mitglieder)|

Die ordnungsgemässe Ladung zur Vollversammlung wurde festgestellt und die Vollversammlung ist mit mehr als 3 Mitgliedern beschlussfähig. Die Tagesordnung wird wie angekündigt durchgeführt. Versammlungsleiter ist Christoph Emonds, Protokollführer Mario Lukas.

# Top 1. Abstimmung "Verlegung des Open Lab Days"
- Vorschlag wieder von Dienstag auf Donnerstag zurück zu legen, da mehr Mitglieder Donnerstags da sein können.
- Neue offizielle Uhrzeit ist 20:00. 

|Stimmen|Anzahl|
|-------|------:|
|Ja|9|
|Nein|0|
|Enthalten|0|

Somit einstimmig angenommen. 10. Mitglied war über Video Konferenz anwesend und hat nicht abgestimmt.

# Top 2. Berichte über Veranstaltungen und Akionen 2018/2019

## 2.1 Veranstaltungen
- Maker Faire Hannover 2018 (VR Reality, Sculpting,  Pauls Kickstarter: PiTablet)
- Lothringair 2018 (Raststätte, Light Painting, Musik durch DigitAC Mitglieder)
- Maker Faire Berlin 2018 (FEZ, FabScan Workshops, Freie Maker, Maker of Merit Award)
- Medica 2018 (Vereins Präsentation, FabScan, Jans Blinkzeug)
- Boxenbau Workshop 5. Mai 2018  ( Bausatz, Bericht Online, Gute vorbereitung, 10 Teilnehmer )
- 3D Drucker Workshop 2018 (Geeetech, 4 Teilnehmer)
- 3D Drucker Workshop 2019 (Geeetech, 6 Teilnehmer), Ergebnis: lieber nicht für Anfänger
- Didacta (Personal Photonics, Jans Blinkzeug)
- Make Munich 2019 (Jans Blinkzeug, Patrick & Felix)
- Aktion Mensch Camp (Workshops: Menschen mit Behinderung, Open Light)
- Maker Faire Berlin 2019 (Rene, Jans Blinkzeug, ... )
- Lumi Blade 19.03.2019 (OLED Wand war defekt und wurde von Chris, Jan, Werner in Berlin abgeholt, Patrick hat das Protokoll reverse engineered)
- Laser World of Photonics 2019 München (Jans Blinkzeug)
- Lothringair 2019 (Nicht mehr so prominent wie Raststätte, gut besucht, Lötworkshops, Jans Blinkzeug)
- Maker Faire Hannover 2019 (Freie Maker im Dark Room, FabScan Stand, Chris Fräse)
- Chaos Communication Camp 2019 (Jans Blinkzeug, Freie Maker Village,  FabScan WorkShop am Freitag)
- Hacker Space US Tour 2019 (Patrick, Felix)

Geplant sind des weiteren:
- Optikmesse am Bodensee im September
- 28.9. und 29.9. Maker Faire Eindhoven
- Oktober Maker Faire Rom

## 2.2 Vorschläge
- Chris regt an Flyer für weitere Veranstalltungen zu drucken
- Rene regt an die alten Workshop Berichte zu übernehem. 
- Es wird angeregt an einer zukünftigen Maker Munich wieder teilzunehmen, sofern sie statt findet
- Christoph regt an eine Weihnachtsfeier zu veranstalten: Vorschlag Glühwein Hack-Over(CCCAC, DigitAC etc.)
	
## 2.2 Entwicklung Makerspace

- Laser Cutter läuft: noch einige Dinge zu verbessern, Chris hat neue Absaugung gebaut
- Neuer Schlüsseltresor:  ist elektronisch, kann E-Mail/Account über App, es gibt Gast- und Hauptzugänge, einen Account für Freie Maker
	
## 2.3 Entwicklung Verein
- Christoph Emonds: 
  - Aktuelle Mitgliedzahlen: 31
  - Kassenbestand: 90,50 Euro (Spendengelder)
  - Mitgliedsbeiträge ab 2019 werden zum ersten mal erhoben und belaufen sich auf 12 Euro im Jahr

# 3. Neuausrichtung Verein	

- Disskusion über eine Neuausrichtung
- Rene stellt fest, dass wir bisher Satzungs-konform gearbeitet haben 
- Es wird diskutiert ob eine direkte Bindung zur Werkstatt notwendig ist 
- Kooperation mit anderen Vereinen wäre eine Möglichkeit (aka Dachverband): Disskusion ergibt,  Dachverband vorerst nicht sinnvoll
- Jan Thar stellt fest, dass es Diverse Anträge und Förderungen durch Projekte gäbe um Reisen/Maschinen/Events zu finanzieren
- Der Verein sollte dennoch eine Professionalisierung anstreben um dadurch Abläufe zu verbessern. 
- Es wird vorgeschlagen, die diversen Organisationspunkte mit Verantwortlichkeiten (bspw. Werkstattmeister, Events/Fortbildung/Kontakt zu anderen Vereinen, Networking/Scouting, Workshops): Dies wird aktuell noch nicht als erforderlich gesehen und für Planungen werden Adhoc-Teams präferiert 

Fazit: Die aktuelle Ausrichtung wird beibehalten, die Werkstatt ist Mittel zum Vereinszweck.

# 4. Neuer Vorstand
- Erläuterung der zu vergebenden Posten 
- Aufstellen geeigeter Kanidaten
   - Jan Thar: 1. Vorsitzender
   - Christopher Werner: Stellvertretender Vorsitzender
   - Christoph Emonds: Beisitzer Kassenwart
   - Felix Plitzko: Beisitzer Kassenprüfer

Alle 4 Kandidaten wurden jeweils einstimmig gewählt und haben die Wahl angenommen. 

|Stimmen|Anzahl|
|-------|------:|
|Ja|10|
|Nein|0|
|Enthalten|0|

11. Mitglied war über Video Konferenz anwesend und hat nicht abgestimmt.

# 5. Konto Eröffnung

- Vorstand bereitet Kontoeröffnung vor
- Termin bei der Sparkasse wird in der nächsten Vorstandssitzung thematisiert

# 6. Sonstiges

## 6.1  Webseite/Kommunikation

- interne Kommunikation primär zur Zeit über Slack ( als Chat Werkzeug )
- Dokumente Erhalt über anderes Tool (Online/oder anders)
- Details werden im Vorstand geklärt
- Social Media Kanäle pflegen
- Versicherung
- über Verbund der offenen Wektstätten
- Unterschied zwischen Werkstatt und Verein
- Vorstand erötert was für Versicherunhg benötigt wird bzw wie und was versichert wird
- Vorstandssitzung einmal im Monat vor oder während dem OpenLab Day (jeder erste Donnerstag im Monat)

## 6.2 Allgemeine Vorschläge

- Geräte (Logbuch, Einweisung, Betreuung, Schulung)
- Weiterer Raum
  - Kleiner Werkstattraum (ehemals Aisler)
  - Aufteilung (Zerspanung/ Elektronik)
- Maker Camp machbar?
  - Zelten  
  - Maker Castle 
  - Hackathon 
  - OLED Wand

Ende: 22:51

Unterschrift Vorstand:

1. Vorstandsvorsitzender (Jan Thar)						

2. Kassenprüfer (Felix Plitzko)

**Comment by Libermentix** [comment]
@JanThar Kannst ja mal versuchen den Issue zu editieren

**Comment by JanThar** [comment]
Ich glaube den Punkt anwesende Vorstände brauchen wir gar nicht (daher auskommentiert), wenn wir den weglassen sieht das glaube ich besser aus bezüglich der eingetragenen Vorstände... Sollte soweit druckbar sein... wobei ich daran gerade scheitere ^^

**Comment by Libermentix** [comment]
@JanThar sieht m.E. gut aus.

**Comment by JanThar** [comment]
Ok, dann die entscheidene Frage: Wie druckt man das?

**Comment by JanThar** [comment]
noch ne kleine Abänderung bezüglich Tagesordung wie geplant durchgeführt Aussage

**Comment by Libermentix** [comment]
Wenn wir mit dem Ding so zufrieden sind, Markdown kopieren, in eine Markdown-Datei .md unter Docs und dann mit referenz auf die Datei diesen Issue schließen würde ich vorschlagen. @JanThar
