### ISSUE TITLE
RetroGamesFestival, verfügbare Konsolen sammeln

### ISSUE THREAD

**Issue by PatrickFranken** [FreieMaker/orga#7]
## Projektname
Für unser erstes RetroGamesFestival benötigen wir eine Liste der Konsolen welche wir zur Verfügung haben.

## Ziel
Bis Ende Oktober sollte bekannt sein, welche Konsolen wir zur Verfügung haben um eventuell noch extern welche besorgen zu können.
Bitte via PR hier sammeln https://github.com/FreieMaker/orga/blob/master/projects/RetroGamesFestival_XMasEdition_2019.md

## Todos
- [x] Mitglieder via Slack fragen
- [x] Aushang im Space

**Comment by Libermentix** [comment]
Hat stattgefunden und spaß gemacht ;-)
