### ISSUE TITLE
RetroGamesFestival, Werbematerial erstellen

### ISSUE THREAD

**Issue by PatrickFranken** [FreieMaker/orga#8]
## Projektname
Das RetroGamesFestival benötigt Werbematerial.

## Ziel
Alles an Material für einen Vorverkauf zu haben.

## Todos
- [x] Flyer erstellen
- [x] Header für Eventbrite Seite erstellen

**Comment by Libermentix** [comment]
Hat stattgefunden und Spaß gemacht!
